# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gem's other website!
email: no-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of files for nightbot commands used in the cannels that
  Gemhunter178 is a moderator in!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pentagonitestudios.com" # the base hostname & protocol for your site
twitter_username: gemhunter178
github_username:  gemhunter178

# Build settings
markdown: kramdown

collections:
  nb:
    output: true
    permalink: /:collection/:name.json
